sudo: false

language: android
dist: trusty

env:
  global:
   - ANDROID_API_LEVEL=28
   - ANDROID_BUILD_TOOLS_VERSION=28.0.3
   - ANDROID_ABI=x86_64
   - ANDROID_TAG=google_apis
   - ADB_INSTALL_TIMEOUT=20

android:
  components:
    - tools

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


before_install:
  - echo y | sdkmanager "platform-tools" >/dev/null
  - echo y | sdkmanager "tools" >/dev/null
  - echo y | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION" >/dev/null
  - echo y | sdkmanager "platforms;android-$ANDROID_API_LEVEL" >/dev/null
  - echo y | sdkmanager "platforms;android-28" >/dev/null
  - echo y | sdkmanager --channel=4 "emulator" >/dev/null
  - echo y | sdkmanager "extras;android;m2repository" >/dev/null
  - echo y | sdkmanager "system-images;android-$ANDROID_API_LEVEL;default;$ANDROID_ABI" >/dev/null

before_script:
  - echo n | android create avd --force -n test -t "android-$ANDROID_API_LEVEL" --abi "$ANDROID_ABI" --tag "$ANDROID_TAG"
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

notification:
  slack:
    on_failure: always
    on_success: change