sudo: false

language: android
dist: trusty

env:
  global:
   - ANDROID_API_LEVEL=26
   - ANDROID_BUILD_TOOLS_VERSION=28.0.3
   - ANDROID_ABI=x86
   - ANDROID_TAG=google_apis
   - ADB_INSTALL_TIMEOUT=20
   - ANDROID_HOME=/usr/local/android-sdk
   - TOOLS=${ANDROID_HOME}/tools
   - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}

android:
  components:
    - tools

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


before_install:
  - echo y | sdkmanager "platform-tools" >/dev/null
  - echo y | sdkmanager "tools" >/dev/null
  - echo y | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION" >/dev/null
  - echo y | sdkmanager "platforms;android-$ANDROID_API_LEVEL" >/dev/null
  - echo y | sdkmanager --channel=4 "emulator" >/dev/null
  - echo y | sdkmanager "extras;android;m2repository" >/dev/null
  - echo y | sdkmanager "system-images;android-$ANDROID_API_LEVEL;default;$ANDROID_ABI" >/dev/null

  - git clone https://github.com/tremby/imgur.sh im
  - chmod a+x im/imgur.sh

  - echo n | avdmanager create avd --force -n test -k "system-images;android-$ANDROID_API_LEVEL;default;$ANDROID_ABI"
  - emulator -verbose -avd test -no-accel -skin 1080x2160 -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0
  - adb shell settings put global transition_animation_scale 0
  - adb shell settings put global animator_duration_scale 0
  - sleep 20

  - adb shell screencap -p /sdcard/screen.png
  - adb pull /sdcard/screen.png
  - ./im/imgur.sh screen.png
  
  - adb shell input keyevent 82
  - sleep 20

  - adb shell screencap -p /sdcard/screen.png
  - adb pull /sdcard/screen.png
  - ./im/imgur.sh screen.png
  - adb shell input keyevent 20
  - sleep 20

  - adb shell screencap -p /sdcard/screen.png
  - adb pull /sdcard/screen.png
  - ./im/imgur.sh screen.png
  - adb shell input keyevent 66
  - sleep 20

  - adb shell screencap -p /sdcard/screen.png
  - adb pull /sdcard/screen.png
  - ./im/imgur.sh screen.png

notification:
  slack:
    on_failure: always
    on_success: change