version: 2

jobs:
  build:
    working_directory: ~/project
    docker:
        - image: circleci/android:api-26-alpha
    steps:
      - run:
          name: Build debug APK
          command: ~/project/gradlew :app:assembleDebug
      - run:
          name: Run Unit Tests
          command: ~/project/gradlew :app:check
      - run:
          name: Run UI Tests
          command: ~/project/gradlew :app:packageDebugAndroidTest
          
