version: 2

jobs:
  build:
    docker:
        - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run:
          name: Build debug APK
          command: ./gradlew :app:assembleDebug
      - run:
          name: Run Unit Tests
          command: ./gradlew :app:check
      - run:
          name: Setup Emulator
          command: |
            echo y | sdkmanager "system-images;android-22;default;armeabi-v7a"
            echo n | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: Start Emulator
          command: |
            export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
            emulator -avd test -noaudio -no-window -accel on
          background: true
      - run:
          name: Wait for Emulator
          command: |
            circle-android wait-for-boot
            adb shell input keyevent 82
      - run:
          name: Run UI Tests
          command: ./gradlew :app:connectedDebugAndroidTest
      - run:
          name: Take Screenshot
          command: |
            git clone https://github.com/tremby/imgur.sh im
            chmod a+x im/imgur.sh
            adb shell screencap -p /sdcard/screen.png
            adb pull /sdcard/screen.png
            ./im/imgur.sh screen.png
      - store_test_results:
          path: ./app/build/reports
