version: 2

jobs:
  build:
    docker:
        - image: circleci/android:api-26-alpha
    steps:
      - run:
          name: LS
          command: ls
      - run:
          name: Build debug APK
          command: ./gradlew :app:assembleDebug
      - run:
          name: Run Unit Tests
          command: ./gradlew :app:check
      - run:
          name: Run UI Tests
          command: ./gradlew :app:packageDebugAndroidTest
          
